#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>

char*generate_name(char*progname, char*file)
{
	char*str;
	unsigned int i;
	str = malloc(sizeof(file) * sizeof(char));
	if(str == NULL)
	{
		printf("\x1B[31;1m%s: Malloc failed?!\x1B[37;0m\r\n", progname);
		exit(5);
	}
	if(isdigit(file[0]))
	{
		printf("\x1B[31;1m%s: File must not begin with a number (%s)!\x1B[37;0m\r\n", progname, file);
		exit(6);
	}
	for(i=0;i<strlen(file);i++)
	{
		str[i] = file[i];
		switch(str[i])
		{
			case ' ':
			case '.':
			case '+':
			case '-':
			case '$':
			case '%':
			case '|':
			case '/':
			case '\\':
				str[i] = '_';
				break;
		}
	}
	return str;
}

int main(int argc, char**argv)
{
	FILE*outfile;
	FILE*infile;
	char**argp;
	if(argc == 1)
	{
		printf("\x1B[31;1m%s: Arguments required!\x1B[37;0m\r\n", argv[0]);
		exit(1);
	}
	if(argc == 2 && (strcmp(argv[1],"-h") == 0 || strcmp(argv[1],"--help") == 0))
	{
		printf("\x1B[1m%s: make a header file containing files in strings\r\n", argv[0]);
		printf("Usage:\x1B[0m \x1B[32m%s \x1B[37;0m <\x1B[34moutfile\x1B[37m> <\x1B[34minfile\x1B[37m> [<\x1B[34minfile\x1B[37m>...]\r\n", argv[0]);
		printf("\r\n");
		printf("\t\x1B[34moutfile\x1B[37m\t\tThe file to output to. \x1B[31mDon't forget the extension!\x1B[37m\r\n");
		printf("\t\x1B[34minfile\x1B[37m...\tThe input files.\r\n");
		exit(0);
	}
	if(argc < 3)
	{
		printf("\x1B[31;1m%s: Too few arguments!\x1B[37;0m\r\n", argv[0]);
		exit(2);
	}
	outfile = fopen(argv[1], "w");
	if(outfile == NULL)
	{
		printf("\x1B[31;1m%s: Can't write to outfile (%s)!\x1B[37;0m\r\n", argv[0], argv[1]);
		exit(4);
	}
	printf("Writing to \"%s\".\r\n", argv[1]);
	fprintf(outfile, "/* Generated by %s. DO NOT EDIT */\r\n\r\n#pragma once\r\n", argv[0]);
	argp = &argv[1];
	while(*++argp != NULL)
	{
		int ch;
		unsigned int filesize, i;
		struct stat st;
		printf("Writing file \"%s\"\r\n", *argp);
		infile = fopen(*argp, "rb");
		if(infile == NULL)
		{
			printf("\x1B[31;1m%s: Can't read from infile (%s)!\x1B[37;0m\r\n", argv[0], *argp);
			exit(7);
		}
		if(fstat(fileno(infile), &st))
		{
			printf("\x1B[31;1m%s: fstat failed (%s)!\x1B[37;0m\r\n", argv[0], *argp);
			return 8;
		}
		filesize = (unsigned)(st.st_size);
		fprintf(outfile, "uint8_t %s[%u] = {",generate_name(argv[0], *argp), filesize);
		for(i=0;i<filesize;i++)
		{
			ch = fgetc(infile);
			if(ch == EOF)
			{
				printf("\x1B[31;1m%s: Error while reading \"%s\"!\x1B[37;0m\r\n", argv[0], *argp);
				return 9;
			}
			if(i)
				fprintf(outfile, ",");
			fprintf(outfile, "0x%02X", ch);
		}
		fprintf(outfile, "};\r\n");
		fclose(infile);
	}
	fprintf(outfile, "/* EOF */\r\n");
	fclose(outfile);
	exit(0);
}
